#!/bin/bash
# Deploy kbennu.com: $ . ./deploy

git add .
git ac "upd"
npm run build
cp -arv build /tmp/
git checkout master
/bin/sleep 4
cp -arv /tmp/build/* .
git add .
git ac "deploy"
git push
git checkout develop
